version: "3.9"

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '10080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.10
    ports:
    - 10080:10080
    - 50051:50051
    volumes:
    - ./artifacts/weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
    network_mode: "host"

  retrieva_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: retrieva_api
    hostname: retrieva_api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEAVIATE_URL=${WEAVIATE_URL}
      - DATA_FOLDER_PATH=${DATA_FOLDER_PATH}
    ports:
      - "3333:3333"
    restart: always
    command: uvicorn api.app:app --host 0.0.0.0 --port 3333
    depends_on:
      - weaviate
    volumes:
      - type: bind # type
        source: ${DATA_FOLDER_PATH}
        target: /code/${DATA_FOLDER_PATH}
    network_mode: "host"

  retrieva_dash:
    container_name: retrieva_dash
    hostname: retrieva_dash
    build:
      context: .
      dockerfile: Dockerfile.dash
    environment:
      - RAG_API_URL=${RAG_API_URL}
    ports:
      - "4444:4444"
    restart: always
    depends_on:
      - retrieva_api
    network_mode: "host"

  ollama_service:
    container_name: ollama_service
    hostname: ollama_service
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    restart: always
    volumes:
    - ./artifacts/ollama_data:/ollama/models
    command: ollama create zephyr-local -f Modelfile; sleep infinity
    network_mode: "host"