FROM public.ecr.aws/docker/library/python:3.10-slim

RUN apt-get update && \
    apt-get upgrade -y && \
    pip install pip --upgrade

WORKDIR /code

COPY ./pyproject.toml /code/pyproject.toml

RUN pip3 install --no-cache-dir .

COPY ./webapp /code/webapp

COPY ./retrieva /code/webapp/retrieva

CMD python3 -m webapp.main
